Add classes
mosidrum/OOP-school-library pull request #1
Opened 2023-08-28 19:06 UTC by mosidrum

I added 3 classes (teacher, person, and student), with teacher and student inheriting the properties of the person class

2023-08-28 19:17 UTC, DammyShittu reviewed
Hi @mosidrum,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that does not have a descriptive readme documentation.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-28 20:03 UTC, Ibizugbe reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme😉. you currently do not have an content under your usage section. kindly do well to add a content relevant to this project to the usage section of your readme👍🏼.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-28 21:13 UTC, mosidrum commented
https://github.com/mosidrum/OOP-school-library/pull/1/commits/2458a64a73ed4926dfef54f1634c2146dbbfc28b

commit link for my readme

2023-08-28 22:14 UTC, Gambit142 requested changes
Hi @mosidrum 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Created `Person` class ✔️ 
- Created `Student` class ✔️ 
- Created `Teacher` class ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-08-28 22:14 UTC, Gambit142 commented on person.rb
> +  end
- [ ] This method will always return false because you are returning false in the end. You could use an **_if...else_** statement or you could simplify the code by doing this 👍 😎:

```ruby
@age >= 18
```

Remember that by default, Ruby always returns the expression of the last statement. 💻 

---

Kindly apply the same logic for the `can_use_services?` method:

```ruby
of_age? || @parent_permission
```

2023-08-28 22:14 UTC, Gambit142 commented on student.rb
> +  end
- [ ] When I try to create an instance of the `Student` class, I get this error:

![image](https://github.com/mosidrum/OOP-school-library/assets/77106962/e6c1bb8e-4165-451f-be0c-d811e4af4523)

---

The `parent_permission` class attribute is passed in as a _**keyword**_ `(parent_permission: true)` argument in the superclass `Person`. Therefore when you call the `super` method in the initialize method of the `Student` class, you need to specify the value that will be passed to the `parent_permission` attribute from the superclass. In this case, you want to pass the value of the `parent_permission` being passed as a parameter when creating an instance of the `Student` class through the `initialize` method to the `parent_permission` attribute when calling super. It is after this that conditions specified in the initialize method of the superclass `Person` will be attainable in the child class `Student`. Kindly take a look at the sample code below 👍 😎:

```ruby
def initialize(age, classroom, name, permission: true)
  super(age, name, parent_permission: permission)
  @classroom = classroom
end
```

Then you can create a new instance of the `Student` class by doing this:

```ruby
student = Student.new(17, 'Music', 'John Doe', parent_permission: false)
```

2023-08-28 22:14 UTC, Gambit142 commented on teacher.rb
> +end
- [ ] When I try to create an instance of the `Teacher` class, I get this error:

![image](https://github.com/mosidrum/OOP-school-library/assets/77106962/081aaa04-6b0b-412b-bfe6-2001963e8ee9)

---

The `parent_permission` class attribute is passed in as a _**keyword**_ `(parent_permission: true)` argument in the superclass `Person`. Therefore when you call the `super` method in the initialize method of the `Teacher` class, you need to specify the value that will be passed to the `parent_permission` attribute from the superclass. In this case, you want to pass the value of the `parent_permission` being passed as a parameter when creating an instance of the `Teacher` class through the `initialize` method to the `parent_permission` attribute when calling super. It is after this that conditions specified in the initialize method of the superclass `Person` will be attainable in the child class `Teacher`. Kindly take a look at the sample code below 👍 😎:

```ruby
def initialize(age, specialization, name, permission: true)
  super(age, name, parent_permission: permission)
  @specialization = specialization
end
```

Then you can create a new instance of the `Student` class by doing this:

```ruby
teacher = Teacher.new(34, 'Math', 'Jane Doe', parent_permission: true)
```

2023-08-29 03:15 UTC, Reem-lab approved these changes
# Hi @mosidrum, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descrtipive PR⭐
- [ ] Kudos for working on the requested changes🤩
- [ ] No Linters error ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 03:22 UTC, merged