add UI prompts
mosidrum/OOP-school-library pull request #5
Opened 2023-08-30 14:52 UTC by mosidrum

I created a form of UI for your school library app

2023-08-30 15:17 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @mosidrum👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with basic UI. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 15:17 UTC, thecodechaser commented on student.rb
> +  h
- [ ] Please remove this unnecessary `h` from here, Users will not be able to start the app because of it.

2023-08-30 15:17 UTC, thecodechaser commented on app.rb
> +  end
- [ ] Please move this code to the `main.rb ` file as requested in the project requirements.

![image](https://github.com/mosidrum/OOP-school-library/assets/83803414/e5908db7-3c11-4951-83f6-65662d592868)

2023-08-30 15:17 UTC, thecodechaser commented on app.rb
> +  end
- [ ] While creating a book, I'm getting the below error, Please make sure to fix this and users should be able to create and display all entities without any error. (Also getting errors while creating student)

![image](https://github.com/mosidrum/OOP-school-library/assets/83803414/5bd152ce-bb19-485f-89d3-ed1e9cf3d60c)

2023-08-31 10:39 UTC, LionRouge1 approved these changes
Hi @mosidrum, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 10:45 UTC, merged